spring.application.name=goldenRetriever
server.port=8181
spring.datasource.url=jdbc:postgresql://localhost:5432/golden_retriever_user
spring.datasource.username=postgres
spring.datasource.password=@Ally5201314
spring.datasource.driver-class-name=org.postgresql.Driver

